@startuml
'https://plantuml.com/activity-diagram-beta

start
:**Cliquer** sur le bouton "Scanner";
:Attente du lecteur RFID\n **Poser** une carte sur le lecteur;
:Recherche dans Dolibarr;
if (Numéro de série connu) then (Oui)
  :Affichage de la fiche adhérent;
else (Non)
  :Demande du nom prénom \n **Cliquer** sur le bouton confirmer;
  if (Nom prénom connus) then (Oui)
    :Affichage de la fiche adhérent;
    :**Cliquer** sur le bouton confirmer;
    :Attente du lecteur RFID \n **Poser** la carte d'un <color red>administrateur</color>;
    if (Numéro de série connu) then (Administrateur)
    :Liaison de l'adhérent;
    else(Non Administeur / inconnu)
    :Message d'erreur;
    endif;
  else (Non)
    :Message d'erreur : la personne n'est pas adhérente;
    :Rendez vous sur adherer.eirlab.net;
  endif;
endif
stop
@enduml
