@startuml
'https://plantuml.com/activity-diagram-beta

start
:**Cliquer** sur le bouton "Débuter un arrivage";
:Attente du lecteur RFID \n **Poser** la carte d'un <color red>administrateur</color>;
fork
:Choix du fournisseur;
fork again
: Sélection du stockage;
end fork
repeat
fork
:Prise de la référence;
fork again
:Scan de la référence;
end fork
repeat while (Références à ajouter ?)
:**Appuyer** sur le bouton "Confirmer";
:Traitement des références;
:Affichage du résumé;
stop

@enduml
