name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    container: ubuntu:22.04
    steps:
      - run: echo "🎉 This job uses runner scale set runners!"
